name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # 1. System Tools Install
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libtool autoconf automake libffi-dev libssl-dev

      # 2. Buildozer Install
      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython==0.29.33

      # 3. Clean Build Environment
      - name: Clean Build
        run: buildozer android clean

      # 4. Start Building APK
      - name: Build APK
        run: buildozer android debug

      # 5. Upload APK to GitHub
      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Updated to v4
        with:
          name: PPSC-Ustad-APK
          path: bin/*.apk
